add Android emulator

diff --git a/.github/actions/test-library-on-nightly/action.yml b/.github/actions/test-library-on-nightly/action.yml
--- a/.github/actions/test-library-on-nightly/action.yml
+++ b/.github/actions/test-library-on-nightly/action.yml
@@ -20,7 +20,28 @@ runs:
       run: |
         cd /tmp/RNApp
         yarn add ${{ inputs.library-npm-package }}
+    - name: Update App.tsx
+      shell: bash
+      run: |
+        cd /tmp/RNApp
+        cat > App.tsx << 'EOF'
+        import React, { useEffect } from 'react';
+        import { View, Text } from 'react-native';
 
+        const App = () => {
+          useEffect(() => {
+            console.log('LOADED_OK');
+          }, []);
+
+          return (
+            <View>
+              <Text>App loaded successfully</Text>
+            </View>
+          );
+        };
+
+        export default App;
+        EOF
     # iOS
     - name: Setup xcode
       if: ${{ inputs.platform == 'ios' }}
@@ -44,11 +65,60 @@ runs:
       if: ${{ inputs.platform == 'android' }}
       uses: actions/setup-java@v2
       with:
-        java-version: '17'
-        distribution: 'zulu'
-    - name: Build Android
-      shell: bash
+        java-version: "17"
+        distribution: "zulu"
+    - name: AVD cache
+      if: ${{ inputs.platform == 'android' }}
+      uses: actions/cache@v4
+      id: avd-cache
+      with:
+        path: |
+          ~/.android/avd/*
+          ~/.android/adb*
+        key: avd-35-arm64-x86_64
+    - name: Enable KVM group perms
       if: ${{ inputs.platform == 'android' }}
       run: |
-        cd /tmp/RNApp/android
-        ./gradlew assembleDebug
+        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+        sudo udevadm control --reload-rules
+        sudo udevadm trigger --name-match=kvm
+        ls /dev/kvm
+
+    - name: Create AVD and generate snapshot for caching
+      if: ${{ inputs.platform == 'android' }} && steps.avd-cache.outputs.cache-hit != 'true'
+      uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2.34.0
+      with:
+        api-level: 35
+        arch: x86_64
+        ram-size: 4096M
+        profile: pixel
+        avd-name: Pixel_3a_API_30_AOSP
+        force-avd-creation: false
+        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+        emulator-boot-timeout: 12000
+        disable-animations: false
+        script: echo "Generated AVD snapshot for caching."
+
+    - name: Build Android
+      if: ${{ inputs.platform == 'android' }}
+      uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2.34.0
+      with:
+        api-level: 35
+        arch: x86_64
+        profile: pixel
+        avd-name: Pixel_3a_API_30_AOSP
+        force-avd-creation: false
+        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+        emulator-boot-timeout: 12000
+        disable-animations: false
+        script: |
+          cd /tmp/RNApp/android
+          ./gradlew installDebug
+          adb shell am start -n com.yourapp/.MainActivity
+          echo "Waiting for app to load..."
+          sleep 10
+          if ! adb logcat -e "LOADED_OK" -d | grep "LOADED_OK"; then
+            echo "❌ 'LOADED_OK' not found in logs"
+            exit 1
+          fi
+          echo "✅ App loaded successfully"
